#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Howler_BP

#include "Basic.hpp"

#include "Howler_BP_classes.hpp"
#include "Howler_BP_parameters.hpp"


namespace SDK
{

// Function Howler_BP.Howler_BP_C.ExecuteUbergraph_Howler_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHowler_BP_C::ExecuteUbergraph_Howler_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "ExecuteUbergraph_Howler_BP");

	Params::Howler_BP_C_ExecuteUbergraph_Howler_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Howler_BP.Howler_BP_C.PlayRunAnim
// (BlueprintCallable, BlueprintEvent)

void AHowler_BP_C::PlayRunAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "PlayRunAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Howler_BP.Howler_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AHowler_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Howler_BP.Howler_BP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHowler_BP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "ReceiveTick");

	Params::Howler_BP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Howler_BP.Howler_BP_C.OnSuccess_EF39D1F748D7143EACEEED91701EE4FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHowler_BP_C::OnSuccess_EF39D1F748D7143EACEEED91701EE4FB(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "OnSuccess_EF39D1F748D7143EACEEED91701EE4FB");

	Params::Howler_BP_C_OnSuccess_EF39D1F748D7143EACEEED91701EE4FB Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Howler_BP.Howler_BP_C.OnFail_EF39D1F748D7143EACEEED91701EE4FB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHowler_BP_C::OnFail_EF39D1F748D7143EACEEED91701EE4FB(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "OnFail_EF39D1F748D7143EACEEED91701EE4FB");

	Params::Howler_BP_C_OnFail_EF39D1F748D7143EACEEED91701EE4FB Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Howler_BP.Howler_BP_C.SetShouldMove
// (Public, BlueprintCallable, BlueprintEvent)

void AHowler_BP_C::SetShouldMove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "SetShouldMove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Howler_BP.Howler_BP_C.CalcLookAtRotation
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyActor                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Target_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHowler_BP_C::CalcLookAtRotation(class AActor* MyActor, class AActor* Target_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "CalcLookAtRotation");

	Params::Howler_BP_C_CalcLookAtRotation Parms{};

	Parms.MyActor = MyActor;
	Parms.Target_0 = Target_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Howler_BP.Howler_BP_C.SetNewSpeed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewSpeed                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AHowler_BP_C::SetNewSpeed(int32 Count, float* NewSpeed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "SetNewSpeed");

	Params::Howler_BP_C_SetNewSpeed Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);

	if (NewSpeed != nullptr)
		*NewSpeed = Parms.NewSpeed;
}


// Function Howler_BP.Howler_BP_C.UpdateSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void AHowler_BP_C::UpdateSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Howler_BP_C", "UpdateSpeed");

	UObject::ProcessEvent(Func, nullptr);
}

}

