#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerStats_UI

#include "Basic.hpp"

#include "PlayerStats_UI_classes.hpp"
#include "PlayerStats_UI_parameters.hpp"


namespace SDK
{

// Function PlayerStats_UI.PlayerStats_UI_C.ExecuteUbergraph_PlayerStats_UI
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayerStats_UI_C::ExecuteUbergraph_PlayerStats_UI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "ExecuteUbergraph_PlayerStats_UI");

	Params::PlayerStats_UI_C_ExecuteUbergraph_PlayerStats_UI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerStats_UI.PlayerStats_UI_C.BndEvt__PlayerStats_UI_KickButton_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UPlayerStats_UI_C::BndEvt__PlayerStats_UI_KickButton_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "BndEvt__PlayerStats_UI_KickButton_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerStats_UI.PlayerStats_UI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPlayerStats_UI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerStats_UI.PlayerStats_UI_C.Update Killed
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPlayerStats_UI_C::Update_Killed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "Update Killed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerStats_UI.PlayerStats_UI_C.GetPingText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UPlayerStats_UI_C::GetPingText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "GetPingText");

	Params::PlayerStats_UI_C_GetPingText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PlayerStats_UI.PlayerStats_UI_C.GetKickButtonVisibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UPlayerStats_UI_C::GetKickButtonVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "GetKickButtonVisibility");

	Params::PlayerStats_UI_C_GetKickButtonVisibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PlayerStats_UI.PlayerStats_UI_C.GetPlayerById
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     PlayerState                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayerStats_UI_C::GetPlayerById(class APlayerState** PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayerStats_UI_C", "GetPlayerById");

	Params::PlayerStats_UI_C_GetPlayerById Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PlayerState != nullptr)
		*PlayerState = Parms.PlayerState;
}

}

