#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Player_AnimBP

#include "Basic.hpp"

#include "Player_AnimBP_classes.hpp"
#include "Player_AnimBP_parameters.hpp"


namespace SDK
{

// Function Player_AnimBP.Player_AnimBP_C.ExecuteUbergraph_Player_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayer_AnimBP_C::ExecuteUbergraph_Player_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "ExecuteUbergraph_Player_AnimBP");

	Params::Player_AnimBP_C_ExecuteUbergraph_Player_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Player_AnimBP.Player_AnimBP_C.AnimNotify_Footstep
// (BlueprintCallable, BlueprintEvent)

void UPlayer_AnimBP_C::AnimNotify_Footstep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "AnimNotify_Footstep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.AnimNotify_JogStart
// (BlueprintCallable, BlueprintEvent)

void UPlayer_AnimBP_C::AnimNotify_JogStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "AnimNotify_JogStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.AnimNotify_IdleStart
// (BlueprintCallable, BlueprintEvent)

void UPlayer_AnimBP_C::AnimNotify_IdleStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "AnimNotify_IdleStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayer_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "BlueprintUpdateAnimation");

	Params::Player_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_70407C274BEF3F98B2074081AD73562C
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_70407C274BEF3F98B2074081AD73562C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_70407C274BEF3F98B2074081AD73562C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_8DDCF4304C2E9BF9AD2B4DBD15E09ADA
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_8DDCF4304C2E9BF9AD2B4DBD15E09ADA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_8DDCF4304C2E9BF9AD2B4DBD15E09ADA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_FC657DF04DEC2D34EB1F5E9D8DA3585F
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_FC657DF04DEC2D34EB1F5E9D8DA3585F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_FC657DF04DEC2D34EB1F5E9D8DA3585F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_4DD6B8964B5A15FEF747B29AC704397C
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_4DD6B8964B5A15FEF747B29AC704397C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_4DD6B8964B5A15FEF747B29AC704397C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_00A020874CAD9BCB7814E49F276A75B6
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_00A020874CAD9BCB7814E49F276A75B6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_00A020874CAD9BCB7814E49F276A75B6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_33A3D98C462B5FDCEE9906AC4E7F6523
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_33A3D98C462B5FDCEE9906AC4E7F6523()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_33A3D98C462B5FDCEE9906AC4E7F6523");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_45D00BC84483FE6E28C0698DDB63CE73
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_45D00BC84483FE6E28C0698DDB63CE73()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_45D00BC84483FE6E28C0698DDB63CE73");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_08797B7044118E77ECE0F4A1FBF52EB3
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_08797B7044118E77ECE0F4A1FBF52EB3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_08797B7044118E77ECE0F4A1FBF52EB3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_FE0BD3544EFC9F6E8F351BB09206DB4B
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_FE0BD3544EFC9F6E8F351BB09206DB4B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_FE0BD3544EFC9F6E8F351BB09206DB4B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_102E54AC4DB20322FC32B68F97E4D11C
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_102E54AC4DB20322FC32B68F97E4D11C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_TransitionResult_102E54AC4DB20322FC32B68F97E4D11C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_ModifyBone_851E529B4BE2F5BD610AF8A256000C92
// (BlueprintEvent)

void UPlayer_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_ModifyBone_851E529B4BE2F5BD610AF8A256000C92()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Player_AnimBP_AnimGraphNode_ModifyBone_851E529B4BE2F5BD610AF8A256000C92");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Player_AnimBP.Player_AnimBP_C.Footstep
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFootstepActionsEnum                    FootstepType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlayer_AnimBP_C::Footstep(EFootstepActionsEnum FootstepType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "Footstep");

	Params::Player_AnimBP_C_Footstep Parms{};

	Parms.FootstepType = FootstepType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Player_AnimBP.Player_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UPlayer_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Player_AnimBP_C", "AnimGraph");

	Params::Player_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

