#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scoreboard_UI

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Scoreboard_UI.Scoreboard_UI_C
// 0x0008 (0x0268 - 0x0260)
class UScoreboard_UI_C final : public UUserWidget
{
public:
	class UScrollBox*                             PlayerContainer;                                   // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Scoreboard_UI_C">();
	}
	static class UScoreboard_UI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScoreboard_UI_C>();
	}
};
static_assert(alignof(UScoreboard_UI_C) == 0x000008, "Wrong alignment on UScoreboard_UI_C");
static_assert(sizeof(UScoreboard_UI_C) == 0x000268, "Wrong size on UScoreboard_UI_C");
static_assert(offsetof(UScoreboard_UI_C, PlayerContainer) == 0x000260, "Member 'UScoreboard_UI_C::PlayerContainer' has a wrong offset!");

}

