#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Water_Ripple_Component

#include "Basic.hpp"

#include "Water_Ripple_Component_classes.hpp"
#include "Water_Ripple_Component_parameters.hpp"


namespace SDK
{

// Function Water_Ripple_Component.Water_Ripple_Component_C.ExecuteUbergraph_Water_Ripple_Component
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWater_Ripple_Component_C::ExecuteUbergraph_Water_Ripple_Component(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Water_Ripple_Component_C", "ExecuteUbergraph_Water_Ripple_Component");

	Params::Water_Ripple_Component_C_ExecuteUbergraph_Water_Ripple_Component Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Water_Ripple_Component.Water_Ripple_Component_C.Cast
// (BlueprintCallable, BlueprintEvent)

void UWater_Ripple_Component_C::Cast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Water_Ripple_Component_C", "Cast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Water_Ripple_Component.Water_Ripple_Component_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UWater_Ripple_Component_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Water_Ripple_Component_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

