#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Confirmation_PopUp_SaveSettings_Theme2

#include "Basic.hpp"

#include "WB_Confirmation_PopUp_SaveSettings_Theme2_classes.hpp"
#include "WB_Confirmation_PopUp_SaveSettings_Theme2_parameters.hpp"


namespace SDK
{

// Function WB_Confirmation_PopUp_SaveSettings_Theme2.WB_Confirmation_PopUp_SaveSettings_Theme2_C.OnClicked_Confirm__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWB_Confirmation_PopUp_SaveSettings_Theme2_C::OnClicked_Confirm__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Confirmation_PopUp_SaveSettings_Theme2_C", "OnClicked_Confirm__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Confirmation_PopUp_SaveSettings_Theme2.WB_Confirmation_PopUp_SaveSettings_Theme2_C.OnClicked_Decline__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWB_Confirmation_PopUp_SaveSettings_Theme2_C::OnClicked_Decline__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Confirmation_PopUp_SaveSettings_Theme2_C", "OnClicked_Decline__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Confirmation_PopUp_SaveSettings_Theme2.WB_Confirmation_PopUp_SaveSettings_Theme2_C.ExecuteUbergraph_WB_Confirmation_PopUp_SaveSettings_Theme2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_Confirmation_PopUp_SaveSettings_Theme2_C::ExecuteUbergraph_WB_Confirmation_PopUp_SaveSettings_Theme2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Confirmation_PopUp_SaveSettings_Theme2_C", "ExecuteUbergraph_WB_Confirmation_PopUp_SaveSettings_Theme2");

	Params::WB_Confirmation_PopUp_SaveSettings_Theme2_C_ExecuteUbergraph_WB_Confirmation_PopUp_SaveSettings_Theme2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_Confirmation_PopUp_SaveSettings_Theme2.WB_Confirmation_PopUp_SaveSettings_Theme2_C.BndEvt__WB_Confirmation_PopUp_SaveSettings_Theme2_WB_Button_Confirmation_Theme2_Right_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWB_Confirmation_PopUp_SaveSettings_Theme2_C::BndEvt__WB_Confirmation_PopUp_SaveSettings_Theme2_WB_Button_Confirmation_Theme2_Right_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Confirmation_PopUp_SaveSettings_Theme2_C", "BndEvt__WB_Confirmation_PopUp_SaveSettings_Theme2_WB_Button_Confirmation_Theme2_Right_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_Confirmation_PopUp_SaveSettings_Theme2.WB_Confirmation_PopUp_SaveSettings_Theme2_C.BndEvt__WB_Confirmation_PopUp_SaveSettings_Theme2_WB_Button_Confirmation_Theme2_Left_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWB_Confirmation_PopUp_SaveSettings_Theme2_C::BndEvt__WB_Confirmation_PopUp_SaveSettings_Theme2_WB_Button_Confirmation_Theme2_Left_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_Confirmation_PopUp_SaveSettings_Theme2_C", "BndEvt__WB_Confirmation_PopUp_SaveSettings_Theme2_WB_Button_Confirmation_Theme2_Left_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

